name: "PHP"
on: [push]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shutdown default MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setting MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql root password: "password"
          mysql database: "application"
      - name: Waiting for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=test --silent; do
            sleep 1
          done
      - name: Environment
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Encryption
        run: php artisan key:generate
      - name: Schemas
        run: php artisan migrate
      - name: Testing
        run: vendor/bin/pest
